# v3 syntax
version: "3"

# Named volumes
volumes:
  # MySQL Data
  project_manager-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: project_manager-mysql
    volumes:
      - project_manager-mysql-data:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=project_manager
      - MYSQL_DATABASE=project_manager
      - MYSQL_USER=project_manager
      - MYSQL_PASSWORD=project_manager
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: project_manager-app
    depends_on:
      - mysql
    volumes:
      - .:/var/www/app
    ports:
      - "8181:8080"
    links:
      - mysql
  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_manager-phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8182:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=project_manager
      - MYSQL_USER=project_manager
      - MYSQL_PASSWORD=project_manager
